# Generated by Django 5.1.1 on 2024-10-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_rename_userid_userprofile_user_credentials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('writer', 'Writer'), ('editor', 'Editor'), ('user', 'User'), ('admin', 'Admin')], max_length=10),
        ),
    ]
