# Generated by Django 5.1.1 on 2024-10-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_editor_id_article_editor_and_more'),
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='editor', to='user_authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('revision', 'Under Revision'), ('archived', 'Archived'), ('published', 'Published')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='writer', to='user_authentication.userprofile'),
        ),
    ]
