# Generated by Django 5.1.1 on 2024-10-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_editor_alter_article_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='article.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('news', 'News'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('opinion', 'Opinion'), ('editorial', 'editorial'), ('featured_topics', 'Featured Topics'), ('environment', 'Environment'), ('sci&tech', 'Science & Tech.')], default='news', max_length=100),
        ),
    ]
