# Generated by Django 5.1.1 on 2024-10-16 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_category_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='article.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('news', 'News'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('opinion', 'Opinion'), ('editorial', 'Editorial'), ('featured_topics', 'Featured Topics'), ('environment', 'Environment'), ('sci_tech', 'Science & Tech.')], default='news', max_length=100),
        ),
    ]
