# Generated by Django 5.1.1 on 2024-11-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_category_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('news', 'News'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('opinion', 'Opinion'), ('editorial', 'editorial'), ('featured_topics', 'Featured Topics'), ('environment', 'Environment'), ('sci_and_tech', 'Science & Tech.')], default='news', max_length=100),
        ),
    ]
