# Generated by Django 5.1.1 on 2024-12-10 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='article.article')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('article', 'date')},
            },
        ),
    ]
