# Generated by Django 5.1.1 on 2024-12-10 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('article', 'Article'), ('feedback', 'Feedback'), ('profile', 'Profile'), ('draft', 'Draft'), ('review', 'Review'), ('publish', 'Publish'), ('article_edit', 'Article Edited'), ('archive', 'Archive'), ('reply', 'Reply to Feedback')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
