# Generated by Django 5.1.1 on 2024-10-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_comment_liked_by_alter_comment_article_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_id',
            new_name='commenter',
        ),
    ]
