# Generated by Django 5.1.1 on 2024-10-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='date_subscribed',
            new_name='subscription_date',
        ),
    ]
