# Generated by Django 5.1.1 on 2024-10-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_rename_date_subscribed_subscription_subscription_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_date',
            new_name='date_subscribed',
        ),
    ]
