# Generated by Django 5.1.1 on 2024-11-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_rename_subscription_date_subscription_date_subscribed'),
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_comments', to='user_authentication.userprofile'),
        ),
    ]
